[package]
name = "ayzim"
version = "0.1.0"
authors = ["Aidan Hobson Sayers <aidanhs@cantab.net>"]
build = "build.rs"

[dependencies]
lazy_static = "0.1.*"
odds = "0.2.11"
serde_json = "0.6.0"
string_cache = { path = "../string-cache" }
phf = "0.7.14"
phf_builder = "0.7.14"
smallvec = "0.1.7"

[build-dependencies]
string_cache_codegen = { path = "../string-cache/string-cache-codegen" }
