pub static ATOMS: &'static [&'static str] = &[
    // from parser.cpp
    "toplevel",
    "defun",
    "block",
    "stat",
    "assign",
    "name",
    "var",
    "const",
    "conditional",
    "binary",
    "return",
    "if",
    "else",
    "while",
    "do",
    "for",
    "seq",
    "sub",
    "call",
    "num",
    "label",
    "break",
    "continue",
    "switch",
    "string",
    "inf",
    "nan",
    "tempRet0",
    "unary-prefix",
    "unary-postfix",
    "Math_fround",
    "SIMD_Float32x4",
    "SIMD_Float64x2",
    "SIMD_Int8x16",
    "SIMD_Int16x8",
    "SIMD_Int32x4",
    "SIMD_Bool8x16",
    "SIMD_Bool16x8",
    "SIMD_Bool32x4",
    "SIMD_Bool64x2",
    "+",
    "-",
    "|",
    "&",
    "^",
    "!",
    "~",
    "<",
    ">=",
    "<=",
    ">",
    "==",
    "!=",
    "/",
    "%",
    "*",
    ">>",
    "<<",
    ">>>",
    "tempDoublePtr",
    "HEAP8",
    "HEAP16",
    "HEAP32",
    "HEAPF32",
    "HEAPU8",
    "HEAPU16",
    "HEAPU32",
    "HEAPF64",
    "f0",
    "",
    "function",
    "(",
    "[",
    "{",
    "}",
    ",",
    "?",
    ":",
    "case",
    "default",
    "dot",
    ".",
    "new",
    "array",
    "object",
    "throw",
    "=",

    // parser.cpp additional in 'keywords'
    "try",
    "catch",
    "finally",
    "true",
    "false",
    "null",
    "enum",
    "this",
    "void",
    "with",

    // optimizer-shared.cpp
    "SIMD_Int8x16_check",
    "SIMD_Int16x8_check",
    "SIMD_Int32x4_check",
    "SIMD_Float32x4_check",
    "SIMD_Float64x2_check",
    "SIMD_Bool8x16_check",
    "SIMD_Bool16x8_check",
    "SIMD_Bool32x4_check",
    "SIMD_Bool64x2_check",

    // optimizer.cpp
    "abort", // eliminateDeadFuncs, isFunctionThatAlwaysThrows
    "in", // RESERVED
    "env", // RESERVED
    "let", // RESERVED
    "___resumeException", // isFunctionThatAlwaysThrows
    "___cxa_throw", // isFunctionThatAlwaysThrows
    "___cxa_rethrow", // isFunctionThatAlwaysThrows
];
